### ISSUE TITLE
Error reading worldgen settings

### ISSUE THREAD

**Issue by Lolothepro** [RyanGar46/Apollo-MC#1]
`[21:15:49] [Render thread/ERROR]: Error reading worldgen settings after loading data packs: Missing referenced custom/removed registry entry for registry ResourceKey[minecraft:root / minecraft:worldgen/noise_settings] named apollo:moon
`

**Comment by the-pink-hacker** [comment]
Fixed. [eb1a9a08f71f4b7bf46220b0558fc74358dd8b31](https://github.com/RyanGar46/Apollo-MC/commit/eb1a9a08f71f4b7bf46220b0558fc74358dd8b31)
